# SPDX-FileCopyrightText: © 2018 Stefano Zacchiroli <zack@upsilon.cc>
# SPDX-FileCopyrightText: © 2018 Martin Michlmayr <tbm@cyrius.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
language: python
python:
  - "3.6"
env:
  - BEANCOUNT="beancount>=2.1.2"
  - BEANCOUNT="git+https://github.com/beancount/beancount/"
matrix:
  allow_failures:
  - env: BEANCOUNT="git+https://github.com/beancount/beancount/"
addons:
  apt:
    packages:
      - cpanminus
      - ledger
install:
  - sudo cpanm --notest --installdeps .
  - pip install $BEANCOUNT
script:
  - make test
